"""Distributed launch script rendering."""

from __future__ import annotations

from pathlib import Path

from ptk.config.schema import PTKConfig
from ptk.distributed.detect import ComputeEnvironment

_TORCHRUN_TEMPLATE = """#!/bin/bash
# Torchrun launch script — generated by posttraining-toolkit
# Usage: ./torchrun.sh <config.yaml>

set -euo pipefail

CONFIG="${{1:?Usage: $0 <config.yaml>}}"
NNODES="${{NNODES:-1}}"
NPROC_PER_NODE="${{NPROC_PER_NODE:-1}}"
MASTER_ADDR="${{MASTER_ADDR:-127.0.0.1}}"
MASTER_PORT="${{MASTER_PORT:-29500}}"

torchrun \\
  --nnodes="$NNODES" \\
  --nproc_per_node="$NPROC_PER_NODE" \\
  --master_addr="$MASTER_ADDR" \\
  --master_port="$MASTER_PORT" \\
  -m ptk.cli run "$CONFIG"
"""

_SLURM_TEMPLATE = """#!/bin/bash
#SBATCH --job-name=ptk-{run_name}
#SBATCH --nodes={nodes}
#SBATCH --ntasks-per-node={gpus_per_node}
#SBATCH --gres=gpu:{gpus_per_node}
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=24:00:00
#SBATCH --output={output_dir}/slurm-%j.out

set -euo pipefail

CONFIG="{config_path}"
export MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_PORT={master_port}
export NNODES=$SLURM_NNODES
export NPROC_PER_NODE={gpus_per_node}

srun torchrun \\
  --nnodes=$NNODES \\
  --nproc_per_node=$NPROC_PER_NODE \\
  --master_addr=$MASTER_ADDR \\
  --master_port=$MASTER_PORT \\
  -m ptk.cli run "$CONFIG"
"""


def render_torchrun_script(config: PTKConfig, output_path: Path) -> Path:
    """Render torchrun launch script."""
    content = _TORCHRUN_TEMPLATE
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    output_path.chmod(0o755)
    return output_path


def render_slurm_script(
    config: PTKConfig,
    env: ComputeEnvironment,
    output_path: Path,
    *,
    master_port: int = 29500,
) -> Path:
    """Render SLURM sbatch script for multi-node training."""
    content = _SLURM_TEMPLATE.format(
        run_name=config.run_name,
        nodes=env.num_nodes,
        gpus_per_node=env.num_gpus,
        config_path=str(output_path.parent / "config.yaml"),
        output_dir=str(config.output_path()),
        master_port=master_port,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    output_path.chmod(0o755)
    return output_path
